version: 2
builds:
- id: "hedged"
  binary: hedged
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/hedged/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: flowerinthenight
    name: hedged
brews:
- repository:
    owner: flowerinthenight
    name: homebrew-tap
  name: hedged
  homepage: "https://github.com/flowerinthenight/hedged"
  description: "A generic daemon based on https://flowerinthenight/hedge/."
  directory: Formula
  install: |
    bin.install "hedged"
  test: |
    assert_match /A generic daemon based on https, shell_output("#{bin}/hedged -h", 0)
