version: 2
builds:
- id: "freyr"
  binary: freyr
  goos:
  - linux
  - darwin
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/freyr/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: flowerinthenight
    name: freyr
brews:
- repository:
    owner: flowerinthenight
    name: homebrew-tap
  name: freyr
  homepage: "https://github.com/flowerinthenight/freyr"
  description: "Companiion service to https://github.com/flowerinthenight/freya/."
  directory: Formula
  install: |
    bin.install "freyr"
  test: |
    assert_match /Companiion service to https, shell_output("#{bin}/freyr -h", 0)
