version: 2
builds:
- id: "groupd"
  binary: groupd
  goos:
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
dist: /tmp/groupd/dist
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: flowerinthenight
    name: groupd
brews:
- repository:
    owner: flowerinthenight
    name: homebrew-tap
  name: groupd
  homepage: "https://github.com/flowerinthenight/groupd"
  description: "Generic cluster service built on hedge."
  directory: Formula
  install: |
    bin.install "groupd"
  test: |
    assert_match /Generic cluster service built on hedge/, shell_output("#{bin}/freyr -h", 0)
